baseURL = 'http://trishandelty.com'
languageCode = 'en-us'
title = 'Trish & Elty'
theme = "portfolio"

# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "green"
  description = "A blog about van life and the outdoors."
  copyright = "&copy;2023 Trish and Elty"
  sidebarAbout = [
    "In February 2023, we're moving into our converted 2016 (Dodge) Ram Promaster 1500. Hit the road with us and discover all the ins and outs of van life, national parks, and being outside while working full time, remotely.",
    "This blog gets updated on a monthly basis, so please check back in a month for an update :)",
  ]

  # email = "you@yoursite.com"

  # Nav links in the side bar

  [[params.navlinks]]
  name = "About"
  url = "about/"
  home = true

  [params.social]
#   facebook      = "full page or profile url in facebook"
#   googleplus    = "full profile url in googleplus"
#   email         = "email@example.com"
#   twitter       = "full profile url in twitter"
#   linkedin      = "full profile url in linkedin"
#   stackoverflow = "full profile url in stackoverflow"
#   instagram     = "full profile url in instagram"
#   github        = "full profile url in github"
#   gitlab        = "full profile url in gitlab"
#   youtube       = "full profile url in youtube"
#   whatsapp      = "wa.me service link"