baseURL = 'http://trishandelty.com'
languageCode = 'en-us'
title = 'Trish & Elty'
theme = "PaperMod"

[params]
    title = 'Trish & Elty'
    description = 'Hit the road with us in our converted 2016 Ram Promaster'
    defaultTheme = 'auto'
    disableThemeToggle = true

[params.assets]
    favicon = "favicon.png"

[[menu.main]]
    identifier = 'about'
    name = 'about'
    url = '/about'
    weight =  10