baseURL = 'http://trishandelty.com'
languageCode = 'en-us'
title = 'Trish & Elty'

[params]
newsletterLink = 'https://docs.google.com/forms/d/e/1FAIpQLSdJbLHj8AUT8i0XxxCNdTzYBLo1vRlDIlJJUYoBzzkkmR-OGQ/viewform'
hisLink = "https://www.instagram.com/eltypls/"
herLink = "https://www.instagram.com/trish_lai/"
pickleLink = "https://www.instagram.com/theshadeywiener/"

[[params.navlinks]]
  name = "Home"
  url = "/"

[[params.navlinks]]
  name = "About"
  url = "about/"